"""Export every local SFM project under a dataset to Metashape artifacts.

The exporter writes two complementary import paths for each project:

* ``metashape_cameras.xml`` is generated by the installed Metashape Python
  runtime and contains camera transforms plus a legacy-compatible calibration.
* ``metashape_reference_ypr.csv`` / ``metashape_reference_opk.csv`` are plain
  Reference-pane imports, while ``points3D.ply`` is a point-cloud import.

The exact COLMAP text model is copied alongside the exports.  This preserves
all FULL_OPENCV parameters, including k5/k6 that Metashape 1.7's XML schema
cannot represent.
"""

from __future__ import annotations

import argparse
import csv
import json
import math
import shutil
import subprocess
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import numpy as np

REPOSITORY_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_SFM_ROOT = REPOSITORY_ROOT / "outputs" / "20260802_150233" / "sfm"
DEFAULT_FALLBACK_IMAGES = (
    DEFAULT_SFM_ROOT / "sfm__custom__aliked_adalam__1000f__PRIMARY" / "images"
)
DEFAULT_METASHAPE = Path(r"C:\Program Files\Agisoft\Metashape Pro\metashape.exe")


@dataclass(frozen=True)
class ColmapCamera:
    camera_id: int
    model: str
    width: int
    height: int
    params: tuple[float, ...]


@dataclass(frozen=True)
class ColmapPose:
    image_id: int
    camera_id: int
    source_name: str
    label: str
    qvec_wxyz: tuple[float, float, float, float]
    t_world_to_camera: np.ndarray
    rotation_world_to_camera: np.ndarray
    rotation_camera_to_world: np.ndarray
    center_world: np.ndarray


@dataclass(frozen=True)
class ColmapPoint:
    point_id: int
    xyz: tuple[float, float, float]
    rgb: tuple[int, int, int]
    error: float


def _basename(value: str) -> str:
    return value.replace("\\", "/").rsplit("/", 1)[-1]


def _normalize_name(value: str) -> str:
    return value.replace("\\", "/").casefold()


def _number(value: float) -> str:
    return f"{float(value):.12f}"


def _quaternion_to_rotation(qvec_wxyz: tuple[float, ...]) -> np.ndarray:
    q = np.asarray(qvec_wxyz, dtype=np.float64)
    if q.shape != (4,) or not np.isfinite(q).all():
        raise ValueError("COLMAP quaternion must contain four finite values")
    norm = float(np.linalg.norm(q))
    if not math.isfinite(norm) or norm <= 1.0e-12:
        raise ValueError(f"invalid COLMAP quaternion norm: {norm}")
    qw, qx, qy, qz = q / norm
    return np.asarray(
        [
            [
                1.0 - 2.0 * (qy * qy + qz * qz),
                2.0 * (qx * qy - qz * qw),
                2.0 * (qx * qz + qy * qw),
            ],
            [
                2.0 * (qx * qy + qz * qw),
                1.0 - 2.0 * (qx * qx + qz * qz),
                2.0 * (qy * qz - qx * qw),
            ],
            [
                2.0 * (qx * qz - qy * qw),
                2.0 * (qy * qz + qx * qw),
                1.0 - 2.0 * (qx * qx + qy * qy),
            ],
        ],
        dtype=np.float64,
    )


def _read_cameras(path: Path) -> dict[int, ColmapCamera]:
    cameras: dict[int, ColmapCamera] = {}
    with path.open("r", encoding="utf-8-sig") as handle:
        for line_number, line in enumerate(handle, start=1):
            fields = line.strip().split()
            if not fields or fields[0].startswith("#"):
                continue
            if len(fields) < 5:
                raise ValueError(f"{path}:{line_number}: invalid COLMAP camera row")
            camera_id = int(fields[0])
            camera = ColmapCamera(
                camera_id=camera_id,
                model=fields[1],
                width=int(fields[2]),
                height=int(fields[3]),
                params=tuple(float(value) for value in fields[4:]),
            )
            if camera_id in cameras:
                raise ValueError(f"{path}:{line_number}: duplicate camera id {camera_id}")
            if camera.width <= 0 or camera.height <= 0:
                raise ValueError(f"{path}:{line_number}: invalid camera dimensions")
            cameras[camera_id] = camera
    if not cameras:
        raise ValueError(f"no camera records found in {path}")
    return cameras


def _read_poses(path: Path) -> list[ColmapPose]:
    poses: list[ColmapPose] = []
    with path.open("r", encoding="utf-8-sig") as handle:
        lines = iter(handle)
        for line_number, line in enumerate(lines, start=1):
            stripped = line.strip()
            if not stripped or stripped.startswith("#"):
                continue
            fields = stripped.split(maxsplit=9)
            if len(fields) != 10:
                raise ValueError(
                    f"{path}:{line_number}: expected 10 COLMAP pose fields, got {len(fields)}"
                )
            try:
                image_id = int(fields[0])
                qvec = tuple(float(value) for value in fields[1:5])
                translation = np.asarray(
                    [float(value) for value in fields[5:8]], dtype=np.float64
                )
                camera_id = int(fields[8])
            except ValueError as error:
                raise ValueError(f"{path}:{line_number}: invalid COLMAP pose row") from error
            source_name = fields[9].replace("\\", "/")
            label = _basename(source_name)
            rotation_wc = _quaternion_to_rotation(qvec)
            rotation_cw = rotation_wc.T
            center = -rotation_cw @ translation
            if not np.isfinite(translation).all() or not np.isfinite(center).all():
                raise ValueError(f"{path}:{line_number}: non-finite camera pose")
            try:
                next(lines)
            except StopIteration as error:
                raise ValueError(f"{path}:{line_number}: missing POINTS2D row") from error
            poses.append(
                ColmapPose(
                    image_id=image_id,
                    camera_id=camera_id,
                    source_name=source_name,
                    label=label,
                    qvec_wxyz=qvec,
                    t_world_to_camera=translation,
                    rotation_world_to_camera=rotation_wc,
                    rotation_camera_to_world=rotation_cw,
                    center_world=center,
                )
            )
    if not poses:
        raise ValueError(f"no registered camera poses found in {path}")
    labels = [pose.label.casefold() for pose in poses]
    if len(labels) != len(set(labels)):
        raise ValueError("camera labels are not unique; a Metashape Reference CSV would be ambiguous")
    return sorted(poses, key=lambda pose: pose.image_id)


def _read_points(path: Path) -> list[ColmapPoint]:
    points: list[ColmapPoint] = []
    with path.open("r", encoding="utf-8-sig") as handle:
        for line_number, line in enumerate(handle, start=1):
            fields = line.strip().split()
            if not fields or fields[0].startswith("#"):
                continue
            if len(fields) < 8:
                raise ValueError(f"{path}:{line_number}: invalid COLMAP 3D point row")
            point_id = int(fields[0])
            xyz = tuple(float(value) for value in fields[1:4])
            rgb = tuple(max(0, min(255, int(float(value)))) for value in fields[4:7])
            error = float(fields[7])
            if len(xyz) != 3 or not np.isfinite(xyz).all() or not math.isfinite(error):
                raise ValueError(f"{path}:{line_number}: non-finite COLMAP point")
            points.append(ColmapPoint(point_id, xyz, rgb, error))
    return points


def _is_model_dir(path: Path) -> bool:
    return (path / "cameras.txt").is_file() and (path / "images.txt").is_file() and (
        path / "points3D.txt"
    ).is_file()


def _select_model_dir(project: Path) -> Path:
    preferred = (
        project / "colmap" / "sparse" / "calibrated_stereo_planar_text",
        project / "colmap" / "sparse" / "0_text",
        project / "sparse" / "0_text",
        project / "colmap" / "experiments" / "calibrated_stereo_planar_8px" / "text",
    )
    for candidate in preferred:
        if _is_model_dir(candidate):
            return candidate
    candidates = [
        path.parent
        for path in project.rglob("images.txt")
        if "export" not in {part.casefold() for part in path.parts}
        and _is_model_dir(path.parent)
    ]
    if not candidates:
        raise FileNotFoundError(f"no complete COLMAP text model found under {project}")
    return sorted(candidates, key=lambda path: ("calibrated_stereo_planar" not in path.name, str(path)))[0]


def _manifest_image_roots(project: Path) -> list[Path]:
    manifest_path = project / "image_manifest.json"
    if not manifest_path.is_file():
        return []
    try:
        manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return []
    roots: list[Path] = []
    for key in ("input_dir", "image_root"):
        value = manifest.get(key)
        if isinstance(value, str) and value:
            roots.append(Path(value))
    return roots


def _image_candidates(root: Path, source_name: str) -> list[Path]:
    normalized = source_name.replace("\\", "/")
    basename = _basename(normalized)
    parts = [part for part in normalized.split("/") if part]
    candidates = [root / Path(*parts), root / basename]
    if parts and parts[0].casefold() in {"left", "right"}:
        candidates.append(root / parts[0] / basename)
    elif basename.casefold().startswith(("left_", "right_")):
        candidates.append(root / basename.split("_", 1)[0] / basename)
    return candidates


def _resolve_images(
    project: Path,
    poses: list[ColmapPose],
    fallback_images: Path | None,
) -> tuple[dict[str, Path], list[str], list[Path]]:
    roots: list[Path] = [project / "images", *_manifest_image_roots(project)]
    if fallback_images is not None:
        roots.append(fallback_images)
    unique_roots: list[Path] = []
    seen_roots: set[str] = set()
    for root in roots:
        resolved = root.expanduser()
        key = str(resolved).casefold()
        if key not in seen_roots and resolved.is_dir():
            seen_roots.add(key)
            unique_roots.append(resolved)

    resolved_images: dict[str, Path] = {}
    missing: list[str] = []
    used_roots: list[Path] = []
    for pose in poses:
        found: Path | None = None
        for root in unique_roots:
            for candidate in _image_candidates(root, pose.source_name):
                if candidate.is_file():
                    found = candidate.resolve()
                    if root not in used_roots:
                        used_roots.append(root)
                    break
            if found is not None:
                break
        if found is None:
            missing.append(pose.source_name)
        else:
            resolved_images[pose.source_name] = found
    return resolved_images, missing, used_roots


def _metashape_ypr(rotation_cw: np.ndarray) -> tuple[float, float, float]:
    r21 = float(np.clip(rotation_cw[2, 1], -1.0, 1.0))
    if r21 > 0.999:
        yaw = math.atan2(float(rotation_cw[1, 0]), float(rotation_cw[0, 0]))
        pitch = math.pi / 2.0
        roll = 0.0
    elif r21 < -0.999:
        yaw = math.atan2(float(rotation_cw[1, 0]), float(rotation_cw[0, 0]))
        pitch = -math.pi / 2.0
        roll = 0.0
    else:
        yaw = math.atan2(-float(rotation_cw[0, 1]), float(rotation_cw[1, 1]))
        roll = math.atan2(-float(rotation_cw[2, 0]), float(rotation_cw[2, 2]))
        pitch = math.asin(r21)
    if yaw > 0.0:
        yaw -= 2.0 * math.pi
    return -math.degrees(yaw), math.degrees(pitch), math.degrees(roll)


def _rx(angle: float) -> np.ndarray:
    c, s = math.cos(angle), math.sin(angle)
    return np.asarray([[1.0, 0.0, 0.0], [0.0, c, -s], [0.0, s, c]])


def _ry(angle: float) -> np.ndarray:
    c, s = math.cos(angle), math.sin(angle)
    return np.asarray([[c, 0.0, s], [0.0, 1.0, 0.0], [-s, 0.0, c]])


def _rz(angle: float) -> np.ndarray:
    c, s = math.cos(angle), math.sin(angle)
    return np.asarray([[c, -s, 0.0], [s, c, 0.0], [0.0, 0.0, 1.0]])


def _metashape_opk(rotation_cw: np.ndarray) -> tuple[tuple[float, float, float], float]:
    u, _, vh = np.linalg.svd(rotation_cw)
    corrected = u @ vh
    if np.linalg.det(corrected) < 0.0:
        u[:, -1] *= -1.0
        corrected = u @ vh
    sine_phi = float(np.clip(corrected[0, 2], -1.0, 1.0))
    phi = math.asin(sine_phi)
    if abs(math.cos(phi)) > 1.0e-10:
        omega = math.atan2(-corrected[1, 2], corrected[2, 2])
        kappa = math.atan2(-corrected[0, 1], corrected[0, 0])
    elif sine_phi > 0.0:
        omega = math.atan2(corrected[1, 0], corrected[1, 1])
        kappa = 0.0
    else:
        omega = math.atan2(-corrected[1, 0], corrected[1, 1])
        kappa = 0.0
    recovered = _rx(omega) @ _ry(phi) @ _rz(kappa)
    roundtrip_error = float(np.max(np.abs(recovered - corrected)))
    angles = np.degrees([omega, phi, kappa]).astype(np.float64)
    return (float(angles[0]), float(angles[1]), float(angles[2])), roundtrip_error


def _write_reference_csv(path: Path, poses: list[ColmapPose], angle_kind: str) -> float:
    if angle_kind == "ypr":
        header = ["label", "x", "y", "z", "yaw", "pitch", "roll"]
    elif angle_kind == "opk":
        header = ["label", "x", "y", "z", "omega", "phi", "kappa"]
    else:
        raise ValueError(f"unsupported Metashape angle kind: {angle_kind}")
    max_roundtrip_error = 0.0
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.writer(handle, lineterminator="\n")
        writer.writerow(header)
        for pose in poses:
            if angle_kind == "ypr":
                angles = _metashape_ypr(pose.rotation_camera_to_world)
            else:
                angles, roundtrip_error = _metashape_opk(pose.rotation_camera_to_world)
                max_roundtrip_error = max(max_roundtrip_error, roundtrip_error)
            values = [*pose.center_world.tolist(), *angles]
            writer.writerow([pose.label, *(_number(value) for value in values)])
    return max_roundtrip_error


def _write_pose_details(
    path: Path,
    poses: list[ColmapPose],
    image_paths: dict[str, Path],
) -> None:
    header = [
        "image_id",
        "camera_id",
        "source_name",
        "label",
        "image_path",
        "x",
        "y",
        "z",
        "qw",
        "qx",
        "qy",
        "qz",
        "yaw",
        "pitch",
        "roll",
        "omega",
        "phi",
        "kappa",
        *(f"r_cw_{row}{column}" for row in range(3) for column in range(3)),
    ]
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.writer(handle, lineterminator="\n")
        writer.writerow(header)
        for pose in poses:
            ypr = _metashape_ypr(pose.rotation_camera_to_world)
            opk, _ = _metashape_opk(pose.rotation_camera_to_world)
            values = [
                pose.image_id,
                pose.camera_id,
                pose.source_name,
                pose.label,
                str(image_paths.get(pose.source_name, "")),
                *(_number(value) for value in pose.center_world),
                *(_number(value) for value in pose.qvec_wxyz),
                *(_number(value) for value in (*ypr, *opk)),
                *(_number(value) for value in pose.rotation_camera_to_world.reshape(-1)),
            ]
            writer.writerow(values)


def _write_points_ply(path: Path, points: list[ColmapPoint]) -> None:
    with path.open("w", encoding="ascii", newline="\n") as handle:
        handle.write("ply\nformat ascii 1.0\n")
        handle.write(f"element vertex {len(points)}\n")
        handle.write("property float x\nproperty float y\nproperty float z\n")
        handle.write("property uchar red\nproperty uchar green\nproperty uchar blue\n")
        handle.write("end_header\n")
        for point in points:
            handle.write(
                "{} {} {} {} {} {}\n".format(
                    *(_number(value) for value in point.xyz),
                    *point.rgb,
                )
            )


def _write_instructions(
    path: Path,
    project: Path,
    model_dir: Path,
    image_roots: list[Path],
    xml_status: dict[str, Any],
) -> None:
    if xml_status.get("status") == "created":
        xml_line = "metashape_cameras.xml is ready; add the listed images and import this camera file."
        if xml_status.get("verified_roundtrip"):
            xml_line += " Its round-trip import was verified headlessly."
        elif xml_status.get("roundtrip", {}).get("status") == "not_run":
            xml_line += " Large-camera headless round-trip verification was not run."
    else:
        xml_line = "metashape_cameras.xml was not generated; use the Reference CSV after adding images."
    text = f"""# Metashape import package

Project: `{project.name}`
COLMAP text model: `{model_dir}`

## Files

- `metashape_cameras.xml`: {xml_line}
- `metashape_reference_ypr.csv`: Reference-pane CSV with `label,x,y,z,yaw,pitch,roll`.
- `metashape_reference_opk.csv`: Reference-pane CSV with `label,x,y,z,omega,phi,kappa`.
- `points3D.ply`: sparse COLMAP tie-point cloud for Metashape point-cloud import.
- `image_list.txt`: absolute image paths used by the XML export.
- `colmap_model/`: exact `cameras.txt`, `images.txt`, and `points3D.txt` source package.
- `metashape_export_manifest.json`: provenance and counts.

## Recommended import order

1. Add the images listed in `image_list.txt` to a new Metashape chunk.
2. Import `metashape_cameras.xml` using the camera import command.
3. If XML import is unavailable, use the Reference pane's Import button with
   `metashape_reference_ypr.csv` and map the seven named columns.
4. Optionally import `points3D.ply` as a point cloud.

Coordinates are local reconstruction coordinates, not GPS. The XML generated
by Metashape 1.7 preserves the usable calibration terms but cannot encode all
COLMAP FULL_OPENCV rational terms; the exact values remain in `colmap_model/`
and the source COLMAP model.

Image roots used while exporting:
{chr(10).join(f"- `{root}`" for root in image_roots) or "- none resolved"}
"""
    path.write_text(text, encoding="utf-8")


def _run_metashape_xml(
    model_dir: Path,
    image_map_path: Path,
    output_path: Path,
    executable: Path,
    *,
    verify_roundtrip: bool,
) -> dict[str, Any]:
    if not executable.is_file():
        return {"status": "skipped", "reason": f"Metashape executable not found: {executable}"}
    runner = REPOSITORY_ROOT / "scripts" / "metashape_camera_xml_export.py"
    verification_path = output_path.with_suffix(".roundtrip.json")
    if verification_path.exists():
        verification_path.unlink()
    command = [
        str(executable.resolve()),
        "-r",
        str(runner.resolve()),
        "--model",
        str(model_dir.resolve()),
        "--image-map",
        str(image_map_path.resolve()),
        "--output",
        str(output_path.resolve()),
    ]
    if verify_roundtrip:
        command.extend(
            [
                "--verify-roundtrip",
                "--verification-output",
                str(verification_path.resolve()),
            ]
        )
    completed = subprocess.run(
        command,
        cwd=str(REPOSITORY_ROOT),
        check=False,
        capture_output=True,
        text=True,
        encoding="utf-8",
        errors="replace",
    )
    log_path = output_path.with_suffix(".metashape.log")
    log_path.write_text(
        "COMMAND:\n"
        + subprocess.list2cmdline(command)
        + "\n\nSTDOUT:\n"
        + completed.stdout
        + "\nSTDERR:\n"
        + completed.stderr,
        encoding="utf-8",
    )
    if completed.returncode != 0 or not output_path.is_file():
        raise RuntimeError(
            f"Metashape XML export failed for {model_dir}; see {log_path} "
            f"(exit code {completed.returncode})"
        )
    result: dict[str, Any] = {
        "status": "created",
        "xml": str(output_path.resolve()),
        "log": str(log_path.resolve()),
        "metashape_executable": str(executable.resolve()),
    }
    if verify_roundtrip:
        if not verification_path.is_file():
            raise RuntimeError(
                f"Metashape XML was written but round-trip verification did not complete; see {log_path}"
            )
        verification = json.loads(verification_path.read_text(encoding="utf-8"))
        if verification.get("aligned_count") != verification.get("pose_count"):
            raise RuntimeError(
                f"Metashape XML round-trip mismatch for {model_dir}: {verification}"
            )
        result.update({"verified_roundtrip": True, "roundtrip": verification})
    else:
        result.update(
            {
                "verified_roundtrip": False,
                "roundtrip": {
                    "status": "not_run",
                    "reason": "large camera set; Metashape 1.7.4 headless import check is avoided",
                },
            }
        )
    return result


def export_project(
    project: Path,
    *,
    fallback_images: Path | None,
    metashape_executable: Path,
    skip_xml: bool,
    verify_max_images: int,
) -> dict[str, Any]:
    model_dir = _select_model_dir(project)
    cameras = _read_cameras(model_dir / "cameras.txt")
    poses = _read_poses(model_dir / "images.txt")
    points = _read_points(model_dir / "points3D.txt")
    verify_roundtrip = not skip_xml and verify_max_images > 0 and len(poses) <= verify_max_images
    unknown_camera_ids = sorted({pose.camera_id for pose in poses} - set(cameras))
    if unknown_camera_ids:
        raise ValueError(f"poses reference missing camera ids: {unknown_camera_ids}")

    image_paths, missing_images, image_roots = _resolve_images(project, poses, fallback_images)
    export_dir = project / "export" / "metashape"
    export_dir.mkdir(parents=True, exist_ok=True)
    colmap_export_dir = export_dir / "colmap_model"
    colmap_export_dir.mkdir(parents=True, exist_ok=True)
    for filename in ("cameras.txt", "images.txt", "points3D.txt"):
        shutil.copy2(model_dir / filename, colmap_export_dir / filename)

    ypr_path = export_dir / "metashape_reference_ypr.csv"
    opk_path = export_dir / "metashape_reference_opk.csv"
    details_path = export_dir / "colmap_pose_details.csv"
    ply_path = export_dir / "points3D.ply"
    image_list_path = export_dir / "image_list.txt"
    image_map_path = export_dir / "image_map.json"
    xml_path = export_dir / "metashape_cameras.xml"
    manifest_path = export_dir / "metashape_export_manifest.json"
    instructions_path = export_dir / "README.md"

    _write_reference_csv(ypr_path, poses, "ypr")
    opk_roundtrip_error = _write_reference_csv(opk_path, poses, "opk")
    _write_pose_details(details_path, poses, image_paths)
    _write_points_ply(ply_path, points)
    image_list_path.write_text(
        "\n".join(str(image_paths[pose.source_name]) for pose in poses if pose.source_name in image_paths)
        + "\n",
        encoding="utf-8",
    )
    image_map_payload = {
        "project": project.name,
        "model_dir": str(model_dir.resolve()),
        "images": [
            {
                "source_name": pose.source_name,
                "label": pose.label,
                "camera_id": pose.camera_id,
                "path": str(image_paths[pose.source_name])
                if pose.source_name in image_paths
                else None,
            }
            for pose in poses
        ],
    }
    image_map_path.write_text(
        json.dumps(image_map_payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )

    if missing_images:
        xml_result: dict[str, Any] = {
            "status": "skipped",
            "reason": "missing images",
            "missing_count": len(missing_images),
            "missing_examples": missing_images[:10],
        }
    elif skip_xml:
        xml_result = {"status": "skipped", "reason": "--skip-xml"}
    else:
        xml_result = _run_metashape_xml(
            model_dir,
            image_map_path,
            xml_path,
            metashape_executable,
            verify_roundtrip=verify_roundtrip,
        )

    manifest = {
        "schema_version": 1,
        "status": "complete" if xml_result.get("status") == "created" else "partial",
        "project": project.name,
        "source_model_dir": str(model_dir.resolve()),
        "source_images_roots": [str(root.resolve()) for root in image_roots],
        "model": {
            "camera_count": len(cameras),
            "registered_image_count": len(poses),
            "point_count": len(points),
            "camera_models": {str(key): value.model for key, value in sorted(cameras.items())},
        },
        "images": {
            "resolved_count": len(image_paths),
            "missing_count": len(missing_images),
            "missing_examples": missing_images[:10],
        },
        "pose_conversion": {
            "colmap": "x_camera = R_world_to_camera @ x_world + t_world_to_camera",
            "camera_center": "C_world = -R_world_to_camera.T @ t_world_to_camera",
            "camera_to_world_rotation": "R_camera_to_world = R_world_to_camera.T",
            "camera_axes": "+X right, +Y down, +Z forward",
            "coordinate_frame": "local, non-georeferenced",
        },
        "quality": {"opk_roundtrip_max_abs_matrix_error": opk_roundtrip_error},
        "outputs": {
            "metashape_xml": xml_result,
            "reference_ypr_csv": str(ypr_path.resolve()),
            "reference_opk_csv": str(opk_path.resolve()),
            "pose_details_csv": str(details_path.resolve()),
            "points_ply": str(ply_path.resolve()),
            "image_list": str(image_list_path.resolve()),
            "image_map": str(image_map_path.resolve()),
            "colmap_model": str(colmap_export_dir.resolve()),
            "instructions": str(instructions_path.resolve()),
        },
    }
    manifest_path.write_text(
        json.dumps(manifest, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )
    _write_instructions(instructions_path, project, model_dir, image_roots, xml_result)
    return manifest


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Export all current SFM projects under a dataset for Metashape."
    )
    parser.add_argument("--sfm-root", type=Path, default=DEFAULT_SFM_ROOT)
    parser.add_argument(
        "--project",
        type=str,
        help="one project directory name/path; by default process every immediate project",
    )
    parser.add_argument(
        "--fallback-images",
        type=Path,
        default=DEFAULT_FALLBACK_IMAGES,
        help="image root used when an older project no longer contains its extracted images",
    )
    parser.add_argument("--metashape-executable", type=Path, default=DEFAULT_METASHAPE)
    parser.add_argument(
        "--verify-max-images",
        type=int,
        default=500,
        help="headlessly round-trip-check XML only for projects up to this many registered cameras",
    )
    parser.add_argument(
        "--skip-xml",
        action="store_true",
        help="write CSV/PLY/COLMAP exports without invoking Metashape",
    )
    return parser.parse_args()


def main() -> int:
    args = _parse_args()
    sfm_root = args.sfm_root.expanduser().resolve()
    if not sfm_root.is_dir():
        raise FileNotFoundError(sfm_root)
    if args.project:
        candidate = Path(args.project).expanduser()
        project = candidate if candidate.is_absolute() else sfm_root / candidate
        projects = [project.resolve()]
    else:
        projects = sorted(path.resolve() for path in sfm_root.iterdir() if path.is_dir())
    if not projects:
        raise ValueError(f"no project directories found under {sfm_root}")

    failures: list[tuple[Path, str]] = []
    for project in projects:
        print(f"=== {project.name} ===")
        try:
            result = export_project(
                project,
                fallback_images=args.fallback_images.expanduser().resolve()
                if args.fallback_images
                else None,
                metashape_executable=args.metashape_executable.expanduser().resolve(),
                skip_xml=args.skip_xml,
                verify_max_images=args.verify_max_images,
            )
            print(
                f"model={result['source_model_dir']}; "
                f"images={result['model']['registered_image_count']}; "
                f"points3D={result['model']['point_count']}; "
                f"status={result['status']}; "
                f"export={project / 'export' / 'metashape'}"
            )
        except Exception as error:  # report all projects before returning failure
            failures.append((project, f"{type(error).__name__}: {error}"))
            print(f"ERROR: {failures[-1][1]}")
    if failures:
        print("\nFailures:")
        for project, message in failures:
            print(f"- {project.name}: {message}")
        return 1
    print(f"\nExported {len(projects)} project(s) for Metashape.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
